version: '3.8'

services:
  telegram-java:
    image: telegram-app-1
    build: .
    ports:
      - "8084:80" # Mapea el puerto 8084 del host al 80 del contenedor
    networks:
      - red-external-network
    restart: always

networks:
  red-external-network:
    external: true
    name: red-external-network  # Asegúrate de que la red externa esté configurada con este nombre
